name: int20h_2020
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  arcore_flutter_plugin: ^0.0.10
  arcore_plugin: ^0.2.0
  flutter_bloc: ^6.1.2
  freezed_annotation: ^0.12.0
  location: ^3.2.4
  google_maps_flutter: ^1.2.0
  geodesy: ^0.3.2
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.0

dev_dependencies:
  freezed: ^0.12.7
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/models/
    - assets/images/
    - assets/icons/
